# Generated by Django 4.1.3 on 2024-01-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='classes',
            field=models.CharField(choices=[('User', 'User'), ('Power User', 'Power User')], default='User', max_length=10),
        ),
    ]
