# Generated by Django 4.1.3 on 2024-01-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_users_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='classes',
            new_name='user_class',
        ),
    ]
